name: git action learning
on: 
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 build-and-test:
   runs-on: ubuntu-latest

    steaps:
     - name: Checkout Code
      uses: actions/checkout@v4

     - name: Enable corepack
       run: corepack enable

     - name: Setup node.js
       uses: actions/setup-nodev@4
       with:
        node-version: '24'
        cache: 'yarn'

     - name: Install Dependency
       run: yarn install
     - name: Typescript command
       run: yarn build             