name: git action learning
on: 
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 build-and-test:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Enable corepack
       run: corepack enable

     - name: Setup node.js
       uses: actions/setup-node@v4
       with:
        node-version: '24'
        cache: 'yarn'

     - name: Install Dependency
       run: yarn install
     - name: Typescript command
       run: yarn build      
     - name: Install railway cli  
       run: npm install -g @railway/cli
     - name: Deploy to railway  
       run: railway up --service ${{secrets.RAILWAY_SERVICE_ID}} --detach
       env: 
        RAILWAY_API_TOKEN: ${{secrets.RAILWAY_TOKEN}}  
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
              
